version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 12
    commands:
      - n 14

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DockerPassword | docker login --username $DockerUsername --password-stdin

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_ARN:latest --build-arg Type --build-arg Role .
      # - docker tag $ECR_REPO_ARN:latest
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS  --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Pushing the Docker image...
      - docker push $ECR_REPO_ARN:latest
      # - echo Writing image definitions file...
      # - printf '[{"name":"%s","imageUri":"%s"}]' $ContainerName $ECR_REPO_ARN:latest > imagedefinitions.json

artifacts:
  type: zip
  base-directory: cfnResources
  files:
    - "**/*"
